let express = require("express"),
  routes = require("./routes"),
  app = require(),
  user = require("./routes/user"),
  db = require("./models"),
  http = require("http"),
  passport = require("passport"),
  passportConfig = require("./config/passport"),
  home = require('./routes')
